### ISSUE TITLE
Suggest Suitable LLM Based on Available Computer Specifications

### ISSUE THREAD

**Issue by Harsh-Avinash** [adarshxs/TokenTally#1]
Implement a feature that, given a user's computer specifications, recommends an appropriate Large Language Model (LLM) that can be efficiently trained or used for inference on that system.

**Details**:

1. User Inputs:
Allow users to input specifications such as:
     - GPU Memory
     - FLOPs per GPU
     - Number of GPUs
     - Memory Bandwidth per GPU
     - CPU specs (optional but can be useful for certain auxiliary tasks or smaller models)
     - Available RAM 
   
2. Model Recommendations:
Based on the entered specifications, provide a list of LLMs that can be efficiently run on the user's system.
Offer details like estimated training time, inference speed, and potential performance metrics.

3. Advanced Features:
Provide potential optimization techniques suitable for their specs to further improve performance or fit larger models.
Suggest potential upgrades or changes to their system for desired models that currently might not fit.

4. Use Cases:
This feature will be particularly useful for researchers, data scientists, and hobbyists looking to leverage LLMs without overstretching or underutilizing their systems.
   
I would want to take up this issue.

**Comment by adarshxs** [comment]
Sure thank you! Assigned it to you

**Comment by adarshxs** [comment]
Ill be closing this issue with regards to #2 . Thank you for the contribution @Harsh-Avinash
